### ISSUE TITLE
Queries

### ISSUE THREAD

**Issue by Ryan2601** [FACN4/Election-Day-App#31]
Queries :

- [x] insertVoters - inserting voters into DB. #32 
- [x] insertRegion - inserting a region into the DB. #33 
- [x] updateVoterStatus - updates the voter status in DB after he has voted. #34 
( check issue #35 for changes made regarding DB schema. )
- [x] insertBoxes - inserting boxes into DB. #38 
- [x] insertUsers - inserting users into DB. #53 
- [x] getVoters - gets voter information by (id/serial number in box/ name). #52 
- [x] getBoxByUser - get box details by user. #54 
- [x] getUserIdByName - get user id by user name #56 
- [x] getNumberOfVotersInBox - get number of voters in a specific box #72 
- [x] Get the number of who already voted in the box #73

**Comment by yoosefkh** [comment]
Done :100:
