### ISSUE TITLE
search for voter

### ISSUE THREAD

**Issue by Ryan2601** [FACN4/Election-Day-App#6]
as a user i want to search for the voter by entering name/id or serial number.
their should be search bar,
when searching it should show all the result within typing in boxes.
i also want to see my box number and the number of voters/who voted.

- [x] create search bar. #14
- [x] create card component(each card contain the search results of voters with their info in it) list. #15
- [x] create information bar component #17 
- [x] make dynamic search. (show while typing)
- [x] populate card list with the relevant results of the search.
- [ ] show 10 suggested names while searching.
- [x] add event listener to every returned result.
