### ISSUE TITLE
setting the database

### ISSUE THREAD

**Issue by tawfiknasser** [FACN4/Election-Day-App#9]
Design and build the data base : 
- [x] design database schema. #10
- [x] build sql file. #18
- [x] Setup the dbconnection file. #19
- [x] build demo file of voters. #11 
- [x] write script to add voters from the demo file to the database. #20
- [x] host on heroku #16

**Comment by tawfiknasser** [comment]
https://www.dbdesigner.net/

**Comment by Ryan2601** [comment]
Demo file has been acquired.

**Comment by tawfiknasser** [comment]
@Ryan2601  confirm if all is done :1st_place_medal:

**Comment by Ryan2601** [comment]
All is done :+1:
